print("Which year were you born?")
year = input("Year: ")
year = int(year)
print("Which birthday number would you like to know?")
number = input("Number: ")
number = int(number)
print(year+number)