print("Hello") 
print("I will add three numbers for you") 
n1 = input("Enter the first number: ") 
n1 = int(n1) 
n2 = input("Enter the second number: ") 
n2 = int(n2) 
n3 = input("Enter the third number: ")
n3 = int(n3)
print("The sum of your numbers is:") 
print(n1+n2+n3)